language: node_js
node_js: stable

# S: Build start
install:
  - npm install


before_script:
  - hexo clean

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "wuhuanhost"
  - git config user.email "post.thinking@gmail.com"
  - git add .
  - git commit -m "update blog......"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build end

branches:
  only:
    - blog

#缓存配置
cache:
  directories:
    - node_modules

env:
 global:
   - GH_REF: github.com/wuhuanhost/wuhuanhost.github.com.git